title: Alireza Kavian
description: Alireza Kavian (alireza kay) Personal Web Page: Software Engineer Student at Khajeh Nasir Toosi University.
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
